export const posts = [
  {
    id: 1,
    category: "dailyTalk",
    title: "롤 브론즈",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: true,
    dislikes: 1,
    content:
      "오늘은 정말 신기한 경험을 했습니다. 롤 브론즈에서 탈출하기 위해 정말 열심히 했는데요, 결과는...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 2,
    category: "infoShare",
    title: "롤 실버",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: true,
    dislikes: 0,
    content:
      "실버 구간에서 가장 중요한 것은 팀워크라고 생각합니다. 그런데도 여전히 혼자 게임하는 사람들이 많아요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 3,
    category: "qAndA",
    title: "롤 골드",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: true,
    dislikes: 2,
    content:
      "골드에 도달했는데, 여기서부터 어떻게 더 올라갈 수 있을까요? 팁이나 추천해주실 분 있나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 4,
    category: "freeDebate",
    title: "롤 플레",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: false,
    dislikes: 1,
    content:
      "플래티넘 구간은 정말 어려운 것 같습니다. 여러 가지 방법을 시도해봤는데 쉽게 승급하지 못하고 있어요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 5,
    category: "advice",
    title: "롤 에메랄드",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: false,
    dislikes: 3,
    content:
      "에메랄드까지 오는데 정말 많은 시간이 걸렸습니다. 여러분들은 어떻게 시간을 관리하면서 게임을 하시나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 6,
    category: "advice",
    title: "롤 다이아몬드",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: true,
    dislikes: 1,
    content:
      "다이아몬드 구간에 오니 팀원들의 실력이 정말 중요해졌습니다. 팀워크가 안 맞으면 쉽게 무너지는 것 같아요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 7,
    category: "dailyTalk",
    title: "롤 마스터",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: false,
    dislikes: 2,
    content:
      "마스터 구간은 진정한 도전의 시작인 것 같습니다. 여기서부터는 정말 실력이 중요해지는 것 같아요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 8,
    category: "qAndA",
    title: "롤 그랜드 마스터",
    author: "별빛여행자",
    date: "24-08-26",
    views: 301,
    likes: 3,
    comments: 3,
    trending: true,
    dislikes: 0,
    content:
      "그랜드 마스터 구간에서 생존하기 위한 팁이 있으신가요? 너무 어려워서 힘들어요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 9,
    category: "infoShare",
    title: "롤 제목 9",
    author: "별빛여행자",
    date: "24-08-26",
    views: 245,
    likes: 12,
    comments: 4,
    trending: true,
    dislikes: 4,
    content:
      "롤 관련 중요한 정보들을 공유하려고 합니다. 패치 노트, 챔피언 가이드 등 유용한 내용들이 많아요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 10,
    category: "dailyTalk",
    title: "롤 제목 10",
    author: "별빛여행자",
    date: "24-08-26",
    views: 310,
    likes: 1,
    comments: 3,
    trending: false,
    dislikes: 5,
    content:
      "오늘은 친구들과 롤을 하면서 재밌는 일들이 많았습니다. 서로 웃고 즐기면서 게임할 수 있는 시간이었어요...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 11,
    category: "advice",
    title: "롤 제목 11",
    author: "별빛여행자",
    date: "24-08-26",
    views: 200,
    likes: 7,
    comments: 2,
    trending: true,
    dislikes: 1,
    content:
      "어떻게 하면 롤에서 더 나은 플레이어가 될 수 있을까요? 저만의 노하우를 공유하고 싶습니다...",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 12,
    category: "freeDebate",
    title: "롤 제목 12",
    author: "별빛여행자",
    date: "24-08-26",
    views: 150,
    likes: 5,
    comments: 1,
    trending: false,
    dislikes: 0,
    content: "다들 브론즈에서 탈출하기 힘든 이유는 무엇인가요? 공유해보아요!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 13,
    category: "infoShare",
    title: "롤 제목 13",
    author: "별빛여행자",
    date: "24-08-26",
    views: 180,
    likes: 8,
    comments: 2,
    trending: true,
    dislikes: 2,
    content:
      "최근 패치에서 바뀐 챔피언에 대해 논의해봅시다. 여러분의 생각은 어떠신가요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 14,
    category: "advice",
    title: "롤 제목 14",
    author: "별빛여행자",
    date: "24-08-26",
    views: 220,
    likes: 4,
    comments: 1,
    trending: false,
    dislikes: 1,
    content: "롤의 매력을 알려주세요! 여러분의 롤을 시작한 계기가 궁금합니다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 15,
    category: "dailyTalk",
    title: "롤 제목 15",
    author: "별빛여행자",
    date: "24-08-26",
    views: 190,
    likes: 6,
    comments: 3,
    trending: true,
    dislikes: 0,
    content: "최근에 해본 롤의 즐거움에 대해 이야기해봅시다!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 16,
    category: "freeDebate",
    title: "롤 제목 16",
    author: "별빛여행자",
    date: "24-08-26",
    views: 170,
    likes: 5,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "어떤 챔피언을 제일 좋아하시나요? 이유도 함께 알려주세요!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 17,
    category: "advice",
    title: "롤 제목 17",
    author: "별빛여행자",
    date: "24-08-26",
    views: 200,
    likes: 3,
    comments: 1,
    trending: true,
    dislikes: 2,
    content:
      "초보자들을 위한 꿀팁이 있다면 공유해주세요! 저도 배워보고 싶어요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 18,
    category: "infoShare",
    title: "롤 제목 18",
    author: "별빛여행자",
    date: "24-08-26",
    views: 220,
    likes: 9,
    comments: 3,
    trending: false,
    dislikes: 1,
    content:
      "팀원이 잘하는 챔피언이 있다면 그걸 보고 배워보세요. 어떤 방법이 좋을까요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 19,
    category: "freeDebate",
    title: "롤 제목 19",
    author: "별빛여행자",
    date: "24-08-26",
    views: 240,
    likes: 12,
    comments: 4,
    trending: true,
    dislikes: 0,
    content: "롤의 그래픽과 스토리에 대해 이야기를 나누어봅시다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 20,
    category: "dailyTalk",
    title: "롤 제목 20",
    author: "별빛여행자",
    date: "24-08-26",
    views: 300,
    likes: 2,
    comments: 5,
    trending: false,
    dislikes: 2,
    content: "친구와의 게임에서 생긴 에피소드를 공유해주세요!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 21,
    category: "infoShare",
    title: "롤 제목 21",
    author: "별빛여행자",
    date: "24-08-26",
    views: 150,
    likes: 4,
    comments: 1,
    trending: true,
    dislikes: 0,
    content: "최근 챔피언 출시 소식에 대해 공유해주세요!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 22,
    category: "advice",
    title: "롤 제목 22",
    author: "별빛여행자",
    date: "24-08-26",
    views: 180,
    likes: 5,
    comments: 2,
    trending: false,
    dislikes: 1,
    content:
      "롤을 잘하기 위한 연습 방법이 있을까요? 여러분의 팁을 듣고 싶어요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 23,
    category: "freeDebate",
    title: "롤 제목 23",
    author: "별빛여행자",
    date: "24-08-26",
    views: 220,
    likes: 8,
    comments: 3,
    trending: true,
    dislikes: 0,
    content:
      "롤의 역사와 발전에 대해 이야기해봅시다. 어떻게 변해왔는지 궁금합니다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 24,
    category: "dailyTalk",
    title: "롤 제목 24",
    author: "별빛여행자",
    date: "24-08-26",
    views: 260,
    likes: 7,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "롤에서 기억에 남는 순간이나 경기 경험을 공유해보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 25,
    category: "infoShare",
    title: "롤 제목 25",
    author: "별빛여행자",
    date: "24-08-26",
    views: 300,
    likes: 3,
    comments: 5,
    trending: true,
    dislikes: 0,
    content: "각 시즌의 메타에 대해 토론해봅시다. 어떤 변화가 있었나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 26,
    category: "advice",
    title: "롤 제목 26",
    author: "별빛여행자",
    date: "24-08-26",
    views: 220,
    likes: 4,
    comments: 2,
    trending: false,
    dislikes: 1,
    content:
      "정말 잘하는 플레이어의 영상을 보고 배워보세요. 어떤 영상을 추천하시나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 27,
    category: "freeDebate",
    title: "롤 제목 27",
    author: "별빛여행자",
    date: "24-08-26",
    views: 240,
    likes: 9,
    comments: 4,
    trending: true,
    dislikes: 0,
    content: "롤과 관련된 다양한 콘텐츠를 추천해봅시다. 책, 영상, 팟캐스트 등!",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 28,
    category: "dailyTalk",
    title: "롤 제목 28",
    author: "별빛여행자",
    date: "24-08-26",
    views: 280,
    likes: 2,
    comments: 3,
    trending: false,
    dislikes: 2,
    content:
      "롤의 인상 깊은 캐릭터에 대해 이야기해보아요. 어떤 캐릭터가 좋나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 29,
    category: "infoShare",
    title: "롤 제목 29",
    author: "별빛여행자",
    date: "24-08-26",
    views: 320,
    likes: 1,
    comments: 5,
    trending: true,
    dislikes: 0,
    content:
      "챔피언의 패치 노트가 나왔습니다. 어떤 변화가 있었는지 살펴보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 30,
    category: "advice",
    title: "롤 제목 30",
    author: "별빛여행자",
    date: "24-08-26",
    views: 220,
    likes: 6,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "경기를 이기기 위한 심리적 접근법에 대해 이야기해봅시다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 31,
    category: "freeDebate",
    title: "롤 제목 31",
    author: "별빛여행자",
    date: "24-08-26",
    views: 210,
    likes: 8,
    comments: 4,
    trending: true,
    dislikes: 0,
    content: "게임에서 겪는 스트레스 해소 방법은 무엇인가요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 32,
    category: "dailyTalk",
    title: "롤 제목 32",
    author: "별빛여행자",
    date: "24-08-26",
    views: 250,
    likes: 7,
    comments: 3,
    trending: false,
    dislikes: 1,
    content: "롤을 통해 생긴 좋은 인연이나 친구들에 대해 공유해주세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 33,
    category: "infoShare",
    title: "롤 제목 33",
    author: "별빛여행자",
    date: "24-08-26",
    views: 270,
    likes: 5,
    comments: 2,
    trending: true,
    dislikes: 0,
    content:
      "챔피언별 카운터 매치업에 대해 알아보아요. 어떤 챔피언이 좋을까요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 34,
    category: "advice",
    title: "롤 제목 34",
    author: "별빛여행자",
    date: "24-08-26",
    views: 290,
    likes: 4,
    comments: 1,
    trending: false,
    dislikes: 2,
    content: "전략적인 플레이를 위한 롤 학습 방법은 무엇인가요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 35,
    category: "freeDebate",
    title: "롤 제목 35",
    author: "별빛여행자",
    date: "24-08-26",
    views: 300,
    likes: 8,
    comments: 3,
    trending: true,
    dislikes: 0,
    content: "경기 중에 겪었던 웃긴 순간들을 나누어보아요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 36,
    category: "dailyTalk",
    title: "롤 제목 36",
    author: "별빛여행자",
    date: "24-08-26",
    views: 310,
    likes: 2,
    comments: 5,
    trending: false,
    dislikes: 1,
    content: "여러분의 롤 아이디는 무엇인가요? 각자 소개해보아요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 37,
    category: "infoShare",
    title: "롤 제목 37",
    author: "별빛여행자",
    date: "24-08-26",
    views: 320,
    likes: 1,
    comments: 4,
    trending: true,
    dislikes: 0,
    content:
      "최근 인기 있는 챔피언은 무엇인가요? 업데이트 내용을 공유해보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 38,
    category: "advice",
    title: "롤 제목 38",
    author: "별빛여행자",
    date: "24-08-26",
    views: 340,
    likes: 3,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "롤을 잘 하기 위한 멘탈 관리 비법이 있다면 무엇인가요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 39,
    category: "freeDebate",
    title: "롤 제목 39",
    author: "별빛여행자",
    date: "24-08-26",
    views: 350,
    likes: 5,
    comments: 3,
    trending: true,
    dislikes: 0,
    content: "게임에 대한 다양한 의견을 나누어봅시다. 어떤 주제가 좋을까요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 40,
    category: "dailyTalk",
    title: "롤 제목 40",
    author: "별빛여행자",
    date: "24-08-26",
    views: 360,
    likes: 4,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "친구와의 롤 대결에서의 승리 경험을 나누어보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 41,
    category: "infoShare",
    title: "롤 제목 41",
    author: "별빛여행자",
    date: "24-08-26",
    views: 370,
    likes: 2,
    comments: 4,
    trending: true,
    dislikes: 0,
    content:
      "롤에서의 다양한 경험담을 공유해보세요. 무엇이 가장 기억에 남나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 42,
    category: "advice",
    title: "롤 제목 42",
    author: "별빛여행자",
    date: "24-08-26",
    views: 380,
    likes: 3,
    comments: 1,
    trending: false,
    dislikes: 1,
    content: "롤에서의 초보자들이 알아야 할 점들을 이야기해봅시다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 43,
    category: "freeDebate",
    title: "롤 제목 43",
    author: "별빛여행자",
    date: "24-08-26",
    views: 390,
    likes: 1,
    comments: 2,
    trending: true,
    dislikes: 0,
    content: "롤의 음악과 사운드트랙에 대해 이야기해보아요. 어떤 곡이 좋나요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 44,
    category: "dailyTalk",
    title: "롤 제목 44",
    author: "별빛여행자",
    date: "24-08-26",
    views: 600 / 400,
    likes: 6,
    comments: 5,
    trending: false,
    dislikes: 1,
    content:
      "여러분의 롤 플레이 스타일은 어떤가요? 전략가, 공격형 등 다양한 스타일이 있죠.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 45,
    category: "infoShare",
    title: "롤 제목 45",
    author: "별빛여행자",
    date: "24-08-26",
    views: 410,
    likes: 2,
    comments: 3,
    trending: true,
    dislikes: 0,
    content:
      "롤에서의 짧은 클립을 공유하고 싶습니다. 재미있는 순간들을 모아보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 46,
    category: "advice",
    title: "롤 제목 46",
    author: "별빛여행자",
    date: "24-08-26",
    views: 420,
    likes: 3,
    comments: 2,
    trending: false,
    dislikes: 1,
    content: "자신의 실력을 향상시키기 위해 가장 먼저 해야 할 것은 무엇일까요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 47,
    category: "freeDebate",
    title: "롤 제목 47",
    author: "별빛여행자",
    date: "24-08-26",
    views: 430,
    likes: 4,
    comments: 1,
    trending: true,
    dislikes: 0,
    content:
      "롤의 미래와 발전 방향에 대해 이야기해봅시다. 어떤 변화가 필요할까요?",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 48,
    category: "dailyTalk",
    title: "롤 제목 48",
    author: "별빛여행자",
    date: "24-08-26",
    views: 440,
    likes: 5,
    comments: 3,
    trending: false,
    dislikes: 1,
    content: "최근에 해본 롤의 재밌는 모드나 이벤트에 대해 공유해주세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 49,
    category: "infoShare",
    title: "롤 제목 49",
    author: "별빛여행자",
    date: "24-08-26",
    views: 450,
    likes: 6,
    comments: 4,
    trending: true,
    dislikes: 0,
    content: "롤에서의 멋진 플레이어와 그들의 기술을 분석해봅시다.",
    imageUrl: "https://picsum.photos/600/400",
  },
  {
    id: 50,
    category: "advice",
    title: "롤 제목 50",
    author: "별빛여행자",
    date: "24-08-26",
    views: 460,
    likes: 7,
    comments: 5,
    trending: false,
    dislikes: 1,
    content: "롤에서의 실패를 극복하는 방법에 대해 공유해보세요.",
    imageUrl: "https://picsum.photos/600/400",
  },
];
