export const mockAnnouncementData = [
    // 전체
    {
        id: 1,
        title: "모든 변경 공지사항을 알려드리려고합니다.",
        category: "입국정보",
        description: "모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.모든 사용자에게 적용되는 중요한 공지사항입니다.",
        date: "2024-10-01",
        imageUrl: "/images/1.jpeg",
        likes: 120,
        disLikes:120,
        popular: 1500,
        comments: 10,
    },
    {
        id: 2,
        title: "전체 시스템 점검 안내",
        category: "입국정보",
        description: "시스템 점검이 예정되어 있습니다. 불편을 드려 죄송합니다.",
        date: "2024-10-03",
        imageUrl: "/images/2.jpeg",
        likes: 95,
        disLikes:120,
        popular: 1200,
        comments: 5,
    },
    {
        id: 3,
        title: "서비스 정책 변경",
        category: "입국정보",
        description: "서비스 이용 정책이 변경되었습니다. 자세한 사항은 공지를 확인하세요.",
        date: "2024-10-05",
        imageUrl: "/images/3.jpeg",
        likes: 80,
        disLikes:120,
        popular: 900,
        comments: 2,
    },
    {
        id: 4,
        title: "새로운 기능 추가 안내",
        category: "이용안내",
        description: "새로운 기능이 추가되었습니다. 업데이트 후 이용해보세요.",
        date: "2024-10-07",
        imageUrl: "/images/4.jpeg",
        likes: 110,
        disLikes:120,
        popular: 1300,
        comments: 15,
    },
    {
        id: 5,
        title: "고객 지원 센터 이전",
        category: "이용안내",
        description: "고객 지원 센터가 새로운 위치로 이전하였습니다.",
        date: "2024-10-09",
        imageUrl: "/images/5.jpeg",
        likes: 70,
        disLikes:120,
        popular: 800,
        comments: 3,
    },

    // 입국정보
    {
        id: 6,
        title: "입국 절차 변경 안내",
        category: "입국정보",
        description: "입국 절차가 변경되었습니다. 변경 사항을 확인하세요.",
        date: "2024-09-28",
        imageUrl: "/images/6.jpeg",
        likes: 60,
        disLikes:120,
        popular: 700,
        comments: 1,
    },
    {
        id: 7,
        title: "비자 발급 절차 안내",
        category: "입국정보",
        description: "비자 발급 절차가 간소화되었습니다. 새로운 절차를 확인하세요.",
        date: "2024-09-30",
        imageUrl: "/images/7.jpeg",
        likes: 50,
        disLikes:120,
        popular: 600,
        comments: 0,
    },
    {
        id: 8,
        title: "입국 심사 강화",
        category: "입국정보",
        description: "입국 심사 절차가 강화되었습니다. 여행 전에 준비하세요.",
        date: "2024-10-01",
        imageUrl: "/images/8.jpeg",
        likes: 85,
        disLikes:120,
        popular: 950,
        comments: 4,
    },
    {
        id: 9,
        title: "자주 묻는 질문: 입국 준비",
        category: "입국정보",
        description: "입국 관련 자주 묻는 질문과 답변을 확인하세요.",
        date: "2024-10-02",
        imageUrl: "/images/8.jpeg",
        likes: 40,
        disLikes:120,
        popular: 300,
        comments: 6,
    },
    {
        id: 10,
        title: "검역 절차 안내",
        category: "입국정보",
        description: "입국 시 검역 절차에 대한 안내입니다.",
        date: "2024-10-04",
        imageUrl: "/images/8.jpeg",
        likes: 30,
        disLikes:120,
        popular: 250,
        comments: 2,
    },
    {
        id: 11,
        title: "최신 입국정보 업데이트",
        category: "입국정보",
        description: "최신 입국정보에 대한 업데이트를 확인하세요.",
        date: "2024-10-05",
        imageUrl: "/images/8.jpeg",
        likes: 20,
        disLikes:120,
        popular: 150,
        comments: 1,
    },
    {
        id: 12,
        title: "입국 조건 변경 안내",
        category: "입국정보",
        description: "입국 조건이 변경되었습니다. 반드시 확인하세요.",
        date: "2024-10-06",
        imageUrl: "/images/8.jpeg",
        likes: 75,
        disLikes:120,
        popular: 800,
        comments: 5,
    },
    {
        id: 13,
        title: "국경 통과 시 유의사항",
        category: "입국정보",
        description: "국경 통과 시 유의사항을 확인하세요.",
        date: "2024-10-07",
        imageUrl: "/images/8.jpeg",
        likes: 65,
        disLikes:120,
        popular: 700,
        comments: 4,
    },
    {
        id: 14,
        title: "입국 시 필요한 서류 안내",
        category: "입국정보",
        description: "입국 시 필요한 서류를 안내드립니다.",
        date: "2024-10-08",
        imageUrl: "/images/8.jpeg",
        likes: 90,
        disLikes:120,
        popular: 900,
        comments: 3,
    },
    {
        id: 15,
        title: "입국 관련 정책 변화",
        category: "입국정보",
        description: "입국 관련 정책이 변경되었습니다. 확인 부탁드립니다.",
        date: "2024-10-09",
        imageUrl: "/images/8.jpeg",
        likes: 55,
        disLikes:120,
        popular: 650,
        comments: 2,
    },

    // 이용안내
    {
        id: 16,
        title: "이용 방법 변경 안내",
        category: "이용안내",
        description: "서비스 이용 방법이 변경되었습니다. 변경된 사항을 확인하세요.",
        date: "2024-10-01",
        imageUrl: "/images/8.jpeg",
        likes: 55,
        disLikes:120,
        popular: 600,
        comments: 3,
    },
    {
        id: 17,
        title: "고객센터 운영 시간 변경",
        category: "이용안내",
        description: "고객센터 운영 시간이 변경되었습니다. 새로운 운영 시간을 확인하세요.",
        date: "2024-10-02",
        imageUrl: "/images/8.jpeg",
        likes: 45,
        disLikes:120,
        popular: 500,
        comments: 1,
    },
    {
        id: 18,
        title: "이용약관 개정 안내",
        category: "이용안내",
        description: "이용약관이 개정되었습니다. 반드시 확인 후 동의 부탁드립니다.",
        date: "2024-10-04",
        imageUrl: "/images/8.jpeg",
        likes: 75,
        disLikes:120,
        popular: 800,
        comments: 8,
    },
    {
        id: 19,
        title: "서비스 개선 사항 안내",
        category: "이용안내",
        description: "서비스 개선 사항을 안내드립니다. 더욱 편리해진 기능을 이용해보세요.",
        date: "2024-10-06",
        imageUrl: "/images/8.jpeg",
        likes: 65,
        disLikes:120,
        popular: 700,
        comments: 2,
    },
    {
        id: 20,
        title: "계정 보안 강화 안내",
        category: "이용안내",
        description: "계정 보안이 강화되었습니다. 더 안전하게 서비스를 이용하세요.",
        date: "2024-10-08",
        imageUrl: "/images/8.jpeg",
        likes: 90,
        disLikes:120,
        popular: 900,
        comments: 5,
    },
    {
        id: 21,
        title: "서비스 FAQ 업데이트",
        category: "이용안내",
        description: "서비스에 대한 FAQ를 업데이트했습니다. 확인해 주세요.",
        date: "2024-10-09",
        imageUrl: "/images/8.jpeg",
        likes: 80,
        disLikes:120,
        popular: 750,
        comments: 4,
    },
    {
        id: 22,
        title: "이용 안내서 다운로드",
        category: "이용안내",
        description: "서비스 이용 안내서를 다운로드할 수 있습니다.",
        date: "2024-10-10",
        imageUrl: "/images/8.jpeg",
        likes: 70,
        disLikes:120,
        popular: 600,
        comments: 3,
    },
    {
        id: 23,
        title: "이용자 의견 수렴 안내",
        category: "이용안내",
        description: "이용자의 소중한 의견을 수렴합니다. 참여해 주세요.",
        date: "2024-10-11",
        imageUrl: "/images/8.jpeg",
        likes: 60,
        disLikes:120,
        popular: 550,
        comments: 2,
    },
    {
        id: 24,
        title: "모바일 앱 이용 안내",
        category: "이용안내",
        description: "모바일 앱을 이용하는 방법을 안내드립니다.",
        date: "2024-10-12",
        imageUrl: "/images/8.jpeg",
        likes: 50,
        disLikes:120,
        popular: 500,
        comments: 1,
    },
    {
        id: 25,
        title: "서비스 이용 시 주의사항",
        category: "이용안내",
        description: "서비스 이용 시 주의사항을 안내드립니다.",
        date: "2024-10-13",
        imageUrl: "/images/8.jpeg",
        likes: 40,
        disLikes:120,
        popular: 450,
        comments: 1,
    },

    // 업데이트
    {
        id: 26,
        title: "서비스 업데이트 공지",
        category: "업데이트",
        description: "서비스 업데이트가 진행됩니다. 확인해 주세요.",
        date: "2024-09-25",
        imageUrl: "/images/8.jpeg",
        likes: 110,
        disLikes:120,
        popular: 1200,
        comments: 10,
    },
    {
        id: 27,
        title: "새로운 기능 추가 안내",
        category: "업데이트",
        description: "새로운 기능이 추가되었습니다. 확인해 주세요.",
        date: "2024-09-26",
        imageUrl: "/images/8.jpeg",
        likes: 100,
        disLikes:120,
        popular: 1100,
        comments: 7,
    },
    {
        id: 28,
        title: "버그 수정 및 개선 사항",
        category: "업데이트",
        description: "버그 수정 및 개선 사항을 안내드립니다.",
        date: "2024-09-28",
        imageUrl: "/images/8.jpeg",
        likes: 95,
        disLikes:120,
        popular: 1000,
        comments: 5,
    },
    {
        id: 29,
        title: "시스템 성능 개선",
        category: "업데이트",
        description: "시스템 성능이 개선되었습니다. 더욱 원활한 서비스를 이용하세요.",
        date: "2024-09-30",
        imageUrl: "/images/8.jpeg",
        likes: 80,
        disLikes:120,
        popular: 900,
        comments: 4,
    },
    {
        id: 30,
        title: "UI/UX 디자인 변경 안내",
        category: "업데이트",
        description: "UI/UX 디자인이 변경되었습니다. 새로운 디자인을 확인하세요.",
        date: "2024-10-01",
        imageUrl: "/images/8.jpeg",
        likes: 70,
        disLikes:120,
        popular: 800,
        comments: 3,
    },
    {
        id: 31,
        title: "알림 기능 개선",
        category: "업데이트",
        description: "알림 기능이 개선되었습니다. 더욱 편리하게 이용해 보세요.",
        date: "2024-10-02",
        imageUrl: "/images/8.jpeg",
        likes: 60,
        disLikes:120,
        popular: 700,
        comments: 2,
    },
    {
        id: 32,
        title: "보안 업데이트 안내",
        category: "업데이트",
        description: "보안 업데이트가 진행되었습니다. 최신 버전으로 업데이트하세요.",
        date: "2024-10-03",
        imageUrl: "/images/8.jpeg",
        likes: 50,
        disLikes:120,
        popular: 600,
        comments: 1,
    },
    {
        id: 33,
        title: "모바일 최적화 업데이트",
        category: "업데이트",
        description: "모바일 최적화를 위한 업데이트가 완료되었습니다.",
        date: "2024-10-04",
        imageUrl: "/images/8.jpeg",
        likes: 40,
        disLikes:120,
        popular: 500,
        comments: 0,
    },
    {
        id: 34,
        title: "소프트웨어 업데이트 일정 안내",
        category: "업데이트",
        description: "소프트웨어 업데이트 일정이 변경되었습니다. 확인해 주세요.",
        date: "2024-10-05",
        imageUrl: "/images/8.jpeg",
        likes: 30,
        disLikes:120,
        popular: 400,
        comments: 1,
    },
    {
        id: 35,
        title: "고객 피드백 반영 업데이트",
        category: "업데이트",
        description: "고객 피드백을 반영하여 업데이트가 진행되었습니다.",
        date: "2024-10-06",
        imageUrl: "/images/8.jpeg",
        likes: 20,
        disLikes:120,
        popular: 300,
        comments: 2,
    },
    {
        id: 36,
        title: "주요 기능 점검 안내",
        category: "업데이트",
        description: "주요 기능 점검이 예정되어 있습니다. 사전에 확인하세요.",
        date: "2024-10-07",
        imageUrl: "/images/8.jpeg",
        likes: 10,
        disLikes:120,
        popular: 200,
        comments: 0,
    },
    {
        id: 37,
        title: "긴급 보안 패치 안내",
        category: "업데이트",
        description: "긴급 보안 패치가 진행되었습니다. 업데이트를 권장합니다.",
        date: "2024-10-08",
        imageUrl: "/images/8.jpeg",
        likes: 5,
        disLikes:120,
        popular: 150,
        comments: 1,
    },

    // 추가 공지사항 (카테고리 별)
    {
        id: 38,
        title: "입국규정 변경 안내",
        category: "입국정보",
        description: "입국 규정이 변경되었습니다. 새로운 규정을 확인하세요.",
        date: "2024-10-08",
        imageUrl: "/images/8.jpeg",
        likes: 90,
        disLikes:120,
        popular: 900,
        comments: 5,
    },
    {
        id: 39,
        title: "비자 정책 변경 안내",
        category: "입국정보",
        description: "비자 정책이 변경되었습니다. 새로운 정책을 확인하세요.",
        date: "2024-10-09",
        imageUrl: "/images/8.jpeg",
        likes: 80,
        disLikes:120,
        popular: 800,
        comments: 4,
    },
    {
        id: 40,
        title: "공항 이용 안내",
        category: "이용안내",
        description: "공항 이용 시 유의사항을 안내드립니다.",
        date: "2024-10-10",
        imageUrl: "/images/8.jpeg",
        likes: 70,
        disLikes:120,
        popular: 700,
        comments: 3,
    },
    {
        id: 41,
        title: "서비스 이용 방법 안내",
        category: "이용안내",
        description: "서비스 이용 방법에 대한 안내입니다.",
        date: "2024-10-11",
        imageUrl: "/images/8.jpeg",
        likes: 60,
        disLikes:120,
        popular: 600,
        comments: 2,
    },
    {
        id: 42,
        title: "고객센터 상담 안내",
        category: "이용안내",
        description: "고객센터 상담 방법에 대한 안내입니다.",
        date: "2024-10-12",
        imageUrl: "/images/8.jpeg",
        likes: 50,
        disLikes:120,
        popular: 500,
        comments: 1,
    },
    {
        id: 43,
        title: "최근 업데이트 확인",
        category: "업데이트",
        description: "최근 업데이트 사항을 확인하세요.",
        date: "2024-10-13",
        imageUrl: "/images/8.jpeg",
        likes: 40,
        disLikes:120,
        popular: 400,
        comments: 0,
    },
    {
        id: 44,
        title: "고객 피드백 반영 계획",
        category: "업데이트",
        description: "고객 피드백을 반영할 계획입니다. 의견 주시면 감사하겠습니다.",
        date: "2024-10-14",
        imageUrl: "/images/8.jpeg",
        likes: 30,
        disLikes:120,
        popular: 300,
        comments: 1,
    },
    {
        id: 45,
        title: "서비스 점검 안내",
        category: "업데이트",
        description: "서비스 점검이 진행될 예정입니다. 일정 확인 바랍니다.",
        date: "2024-10-15",
        imageUrl: "/images/8.jpeg",
        likes: 20,
        disLikes:120,
        popular: 200,
        comments: 2,
    },
    {
        id: 46,
        title: "시스템 안정성 향상",
        category: "업데이트",
        description: "시스템 안정성을 향상시키는 업데이트가 진행됩니다.",
        date: "2024-10-16",
        imageUrl: "/images/8.jpeg",
        likes: 15,
        disLikes:120,
        popular: 150,
        comments: 0,
    },
    {
        id: 47,
        title: "고객 서비스 향상 계획",
        category: "업데이트",
        description: "고객 서비스 향상 계획을 안내드립니다.",
        date: "2024-10-17",
        imageUrl: "/images/8.jpeg",
        likes: 10,
        disLikes:120,
        popular: 100,
        comments: 1,
    },
    {
        id: 48,
        title: "비자 발급 절차 안내",
        category: "입국정보",
        description: "비자 발급 절차에 대한 안내입니다.",
        date: "2024-10-18",
        imageUrl: "/images/8.jpeg",
        likes: 90,
        disLikes:120,
        popular: 900,
        comments: 3,
    },
    {
        id: 49,
        title: "여행자 안전 가이드",
        category: "입국정보",
        description: "여행자를 위한 안전 가이드를 안내드립니다.",
        date: "2024-10-19",
        imageUrl: "/images/8.jpeg",
        likes: 80,
        disLikes:120,
        popular: 800,
        comments: 2,
    },
    {
        id: 50,
        title: "항공편 예약 안내",
        category: "이용안내",
        description: "항공편 예약에 대한 안내입니다.",
        date: "2024-10-20",
        imageUrl: "/images/8.jpeg",
        likes: 70,
        disLikes:120,
        popular: 700,
        comments: 4,
    },
    {
        id: 51,
        title: "여행 시 유의사항",
        category: "이용안내",
        description: "여행 시 유의사항을 안내드립니다.",
        date: "2024-10-21",
        imageUrl: "/images/8.jpeg",
        likes: 60,
        disLikes:120,
        popular: 600,
        comments: 2,
    },
    {
        id: 52,
        title: "고객 응대 매뉴얼",
        category: "이용안내",
        description: "고객 응대 매뉴얼을 안내드립니다.",
        date: "2024-10-22",
        imageUrl: "/images/8.jpeg",
        likes: 50,
        disLikes:120,
        popular: 500,
        comments: 1,
    },
    {
        id: 53,
        title: "서비스 운영 방침 안내",
        category: "업데이트",
        description: "서비스 운영 방침을 안내드립니다.",
        date: "2024-10-23",
        imageUrl: "/images/8.jpeg",
        likes: 40,
        disLikes:120,
        popular: 400,
        comments: 0,
    },
    {
        id: 54,
        title: "여행 보험 안내",
        category: "이용안내",
        description: "여행 보험에 대한 안내입니다.",
        date: "2024-10-24",
        imageUrl: "/images/8.jpeg",
        likes: 30,
        disLikes:120,
        popular: 300,
        comments: 1,
    },
    {
        id: 55,
        title: "공식 웹사이트 리뉴얼",
        category: "이벤트",
        description: "공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.공식 웹사이트가 리뉴얼되었습니다. 새로운 모습을 확인하세요.",
        date: "2024-10-25",
        imageUrl: "",
        likes: 20,
        disLikes:120,
        popular: 200,
        comments: 2,
    },
];
