import Sidebar from "@/core/components/side-bar/Sidebar";
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./auth/provider";
import ReactQueryProvider from "@/core/utils/reactQueryProvider";
import Topbar from "@/core/components/top-bar/Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="bg-[#F6F6F6]">
        <ReactQueryProvider>
          <AuthProvider>
            <Topbar />
            <Sidebar />
            <div className="ml-64 pt-[80px]">
              {children}
            </div>
              {modal}

          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
