import Sidebar from "@/core/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/core/components/Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <Sidebar />
        <main className="ml-64 pt-16 p-4"> {children}</main>
      </body>
    </html>
  );
}
